// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stream_stats/stream_stats.proto

package stream_stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsRequest) Reset() {
	*x = UserStatsRequest{}
	mi := &file_stream_stats_stream_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRequest) ProtoMessage() {}

func (x *UserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stats_stream_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRequest.ProtoReflect.Descriptor instead.
func (*UserStatsRequest) Descriptor() ([]byte, []int) {
	return file_stream_stats_stream_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StreamStats         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_stream_stats_stream_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stats_stream_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_stream_stats_stream_stats_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsResponse) GetStats() []*StreamStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatsRequest) Reset() {
	*x = StreamStatsRequest{}
	mi := &file_stream_stats_stream_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatsRequest) ProtoMessage() {}

func (x *StreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stats_stream_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_stream_stats_stream_stats_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStatsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StreamStats         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatsResponse) Reset() {
	*x = StreamStatsResponse{}
	mi := &file_stream_stats_stream_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatsResponse) ProtoMessage() {}

func (x *StreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stats_stream_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatsResponse.ProtoReflect.Descriptor instead.
func (*StreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_stream_stats_stream_stats_proto_rawDescGZIP(), []int{3}
}

func (x *StreamStatsResponse) GetStats() []*StreamStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StreamStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamId       string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId         string                 `protobuf:"bytes,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Date           string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Airtime        int32                  `protobuf:"varint,6,opt,name=airtime,proto3" json:"airtime,omitempty"`
	PeakViewers    int32                  `protobuf:"varint,7,opt,name=peak_viewers,json=peakViewers,proto3" json:"peak_viewers,omitempty"`
	AverageViewers int32                  `protobuf:"varint,8,opt,name=average_viewers,json=averageViewers,proto3" json:"average_viewers,omitempty"`
	HoursWatched   int32                  `protobuf:"varint,9,opt,name=hours_watched,json=hoursWatched,proto3" json:"hours_watched,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamStats) Reset() {
	*x = StreamStats{}
	mi := &file_stream_stats_stream_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStats) ProtoMessage() {}

func (x *StreamStats) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stats_stream_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStats.ProtoReflect.Descriptor instead.
func (*StreamStats) Descriptor() ([]byte, []int) {
	return file_stream_stats_stream_stats_proto_rawDescGZIP(), []int{4}
}

func (x *StreamStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamStats) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamStats) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StreamStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StreamStats) GetAirtime() int32 {
	if x != nil {
		return x.Airtime
	}
	return 0
}

func (x *StreamStats) GetPeakViewers() int32 {
	if x != nil {
		return x.PeakViewers
	}
	return 0
}

func (x *StreamStats) GetAverageViewers() int32 {
	if x != nil {
		return x.AverageViewers
	}
	return 0
}

func (x *StreamStats) GetHoursWatched() int32 {
	if x != nil {
		return x.HoursWatched
	}
	return 0
}

var File_stream_stats_stream_stats_proto protoreflect.FileDescriptor

const file_stream_stats_stream_stats_proto_rawDesc = "" +
	"\n" +
	"\x1fstream_stats/stream_stats.proto\x12\fstream_stats\"+\n" +
	"\x10UserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x11UserStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x03(\v2\x19.stream_stats.StreamStatsR\x05stats\"1\n" +
	"\x12StreamStatsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"F\n" +
	"\x13StreamStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x03(\v2\x19.stream_stats.StreamStatsR\x05stats\"\x8b\x02\n" +
	"\vStreamStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x04 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x18\n" +
	"\aairtime\x18\x06 \x01(\x05R\aairtime\x12!\n" +
	"\fpeak_viewers\x18\a \x01(\x05R\vpeakViewers\x12'\n" +
	"\x0faverage_viewers\x18\b \x01(\x05R\x0eaverageViewers\x12#\n" +
	"\rhours_watched\x18\t \x01(\x05R\fhoursWatched2\xbc\x01\n" +
	"\x12StreamStatsService\x12O\n" +
	"\fGetUserStats\x12\x1e.stream_stats.UserStatsRequest\x1a\x1f.stream_stats.UserStatsResponse\x12U\n" +
	"\x0eGetStreamStats\x12 .stream_stats.StreamStatsRequest\x1a!.stream_stats.StreamStatsResponseB\x16Z\x14./proto/stream_statsb\x06proto3"

var (
	file_stream_stats_stream_stats_proto_rawDescOnce sync.Once
	file_stream_stats_stream_stats_proto_rawDescData []byte
)

func file_stream_stats_stream_stats_proto_rawDescGZIP() []byte {
	file_stream_stats_stream_stats_proto_rawDescOnce.Do(func() {
		file_stream_stats_stream_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_stats_stream_stats_proto_rawDesc), len(file_stream_stats_stream_stats_proto_rawDesc)))
	})
	return file_stream_stats_stream_stats_proto_rawDescData
}

var file_stream_stats_stream_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stream_stats_stream_stats_proto_goTypes = []any{
	(*UserStatsRequest)(nil),    // 0: stream_stats.UserStatsRequest
	(*UserStatsResponse)(nil),   // 1: stream_stats.UserStatsResponse
	(*StreamStatsRequest)(nil),  // 2: stream_stats.StreamStatsRequest
	(*StreamStatsResponse)(nil), // 3: stream_stats.StreamStatsResponse
	(*StreamStats)(nil),         // 4: stream_stats.StreamStats
}
var file_stream_stats_stream_stats_proto_depIdxs = []int32{
	4, // 0: stream_stats.UserStatsResponse.stats:type_name -> stream_stats.StreamStats
	4, // 1: stream_stats.StreamStatsResponse.stats:type_name -> stream_stats.StreamStats
	0, // 2: stream_stats.StreamStatsService.GetUserStats:input_type -> stream_stats.UserStatsRequest
	2, // 3: stream_stats.StreamStatsService.GetStreamStats:input_type -> stream_stats.StreamStatsRequest
	1, // 4: stream_stats.StreamStatsService.GetUserStats:output_type -> stream_stats.UserStatsResponse
	3, // 5: stream_stats.StreamStatsService.GetStreamStats:output_type -> stream_stats.StreamStatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_stats_stream_stats_proto_init() }
func file_stream_stats_stream_stats_proto_init() {
	if File_stream_stats_stream_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_stats_stream_stats_proto_rawDesc), len(file_stream_stats_stream_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_stats_stream_stats_proto_goTypes,
		DependencyIndexes: file_stream_stats_stream_stats_proto_depIdxs,
		MessageInfos:      file_stream_stats_stream_stats_proto_msgTypes,
	}.Build()
	File_stream_stats_stream_stats_proto = out.File
	file_stream_stats_stream_stats_proto_goTypes = nil
	file_stream_stats_stream_stats_proto_depIdxs = nil
}
