// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StreamStat struct {
	ID             int32       `db:"id" json:"id"`
	StreamID       string      `db:"stream_id" json:"stream_id"`
	UserID         string      `db:"user_id" json:"user_id"`
	GameID         string      `db:"game_id" json:"game_id"`
	Date           pgtype.Date `db:"date" json:"date"`
	Airtime        pgtype.Int4 `db:"airtime" json:"airtime"`
	PeakViewers    pgtype.Int4 `db:"peak_viewers" json:"peak_viewers"`
	AverageViewers pgtype.Int4 `db:"average_viewers" json:"average_viewers"`
	HoursWatched   pgtype.Int4 `db:"hours_watched" json:"hours_watched"`
}
