// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStreamStats = `-- name: InsertStreamStats :exec
INSERT INTO stream_stats (
    stream_id, user_id, game_id, date, airtime, peak_viewers, average_viewers, hours_watched
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) ON CONFLICT (stream_id, date)
DO UPDATE SET
    airtime = EXCLUDED.airtime,
    peak_viewers = GREATEST(stream_stats.peak_viewers, EXCLUDED.peak_viewers),
    average_viewers = ROUND(stream_stats.average_viewers + EXCLUDED.average_viewers) / 2,
    hours_watched = stream_stats.hours_watched + ROUND(EXCLUDED.average_viewers * (EXCLUDED.airtime / 60.0))
`

type InsertStreamStatsParams struct {
	StreamID       string      `db:"stream_id" json:"stream_id"`
	UserID         string      `db:"user_id" json:"user_id"`
	GameID         string      `db:"game_id" json:"game_id"`
	Date           pgtype.Date `db:"date" json:"date"`
	Airtime        pgtype.Int4 `db:"airtime" json:"airtime"`
	PeakViewers    pgtype.Int4 `db:"peak_viewers" json:"peak_viewers"`
	AverageViewers pgtype.Int4 `db:"average_viewers" json:"average_viewers"`
	HoursWatched   pgtype.Int4 `db:"hours_watched" json:"hours_watched"`
}

func (q *Queries) InsertStreamStats(ctx context.Context, arg InsertStreamStatsParams) error {
	_, err := q.db.Exec(ctx, insertStreamStats,
		arg.StreamID,
		arg.UserID,
		arg.GameID,
		arg.Date,
		arg.Airtime,
		arg.PeakViewers,
		arg.AverageViewers,
		arg.HoursWatched,
	)
	return err
}
