name: Golang Tritch Parcer CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      # - name: Build binary
      #   run: go build -v -o tritchgo ./cmd

      - name: Run tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t tritchgo:latest .

      - name: Scan image
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: tritchgo:latest
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Log in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/tritchgo:${{ github.sha }}
          docker tag tritchgo:latest $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push
        run: |
          docker push $IMAGE_TAG
          docker tag tritchgo:latest ghcr.io/${{ github.repository_owner }}/tritchgo:latest
          docker push ghcr.io/${{ github.repository_owner }}/tritchgo:latest
